contract: 0.1 # contract版本信息

package: com.contract.service.user # 包名
version: 1.0 # 版本
title: 用户服务 # 标题
description: 用户服务描述信息 # 描述

dependencies: # 包依赖 (使用其他包的资源)
  - package: com.contract.service.a.account
    version: 0.1
  - package: com.contract.service.b.account
    version: 0.1
    name: accountb # 别名

structs: # 数据定义
  - name: Sex
    title: 性别
    description: 用户性别只能是男或女?
    fields: # 枚举列表
    - key: male
      value: 1
      title: 男
    - key: female
      value: 2
      title: 女
  - name: UserInfo
    title: 用户信息
    fields: # 属性列表
      - name: userName
        title: 用户名
        type: String
        checks:
          - name: chars
      - name: sex
        title: 用户性别
        type: Sex
        optional: false # 直接验证器
      - name: tags
        title: 用户标签列表
        type: <String>
  - name: LoginRequest
    fields:
      - field: userName
        checks:
          - name: chars
      - name: password
        title: 密码
        type: String
      - name: email
        title: 邮箱
        type: String
        format: email

fields: # 字段单独定义
  - name: userName
    title: 用户名
    type: String

validaters: # 定义验证器
  - name: password
    type: String
    title: 密码格式
    regexp: /\d+/

services: # 服务定义
  - name: Account
    title: 账户服务
    auth: true
  - name: Auth
    title: 授权服务
    method: POST # 默认的请求方法
    - actions: # 服务定义
      - name: Login
        auth: false
        title: 登录
        method: POST
        path: account/:login
        request: LoginRequest
        response: accountb.LoginResponse

pages: # 定义页面
  - name: Home
    title: Home

views: # 定义视图
  - name: About
    title: About
    path: /about
